/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Utilitarios.Validacion;
import java.util.HashMap;
/**
 *
 * @author Karlo
 */
public class Ingresos extends javax.swing.JDialog {
    int xa,ya;
    /**
     * Creates new form Ingresos
     */
    boolean estado;
    HashMap<String,int[]> nodos;
    public Ingresos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        estado=false;
        error.setVisible(false);
        error2.setVisible(false);
    }                                               
    public void setNodos(HashMap<String,int[]> nodos,boolean nodo,String arista){
        this.nodos=nodos;
        if(!nodo){
            nombre.setText("Arista");
            ingreso.setText(arista);
            ingreso.setEnabled(false);
        }
    }
    public boolean getState(){
        return estado;
    }
    public String getNombre(){
        return ingreso.getText();
    }
    public float getValor(){
        return Float.valueOf(valor.getText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        ingreso = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        error2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Nombre");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 82, -1));

        ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoActionPerformed(evt);
            }
        });
        ingreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ingresoKeyPressed(evt);
            }
        });
        getContentPane().add(ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 109, -1));

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 110, 90, -1));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 82, -1));

        error.setFont(new java.awt.Font("TINspireKeysCX", 0, 13)); // NOI18N
        error.setForeground(new java.awt.Color(255, 51, 51));
        error.setText("X");
        error.setToolTipText("Error de nombre");
        getContentPane().add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 15, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Valor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        valor.setText("0");
        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });
        valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valorKeyPressed(evt);
            }
        });
        getContentPane().add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 109, -1));

        error2.setFont(new java.awt.Font("TINspireKeysCX", 0, 13)); // NOI18N
        error2.setForeground(new java.awt.Color(255, 51, 51));
        error2.setText("X");
        error2.setToolTipText("Error de valor");
        getContentPane().add(error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 15, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 25, 120, 10));

        titulo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Ingreso");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 3, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        evaluar();
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoActionPerformed

    private void ingresoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresoKeyPressed
        //print(evt.getKeyCode());
        if(evt.getKeyCode()==10){
            evaluar();
        }
    }//GEN-LAST:event_ingresoKeyPressed

    private void ingresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresoKeyTyped
        int nc=evt.getKeyChar();
        if((nc<"a".charAt(0) || nc >"z".charAt(0)) && (nc<"A".charAt(0) || nc >"Z".charAt(0))){
            evt.consume();
        }else{if(ingreso.getText().length()>0){evt.consume();}}
    }//GEN-LAST:event_ingresoKeyTyped

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorActionPerformed

    private void valorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorKeyTyped
        int nc=evt.getKeyChar();
        if((nc<"0".charAt(0) || nc >"9".charAt(0)) && nc!="-".charAt(0) && nc!=".".charAt(0)){
            evt.consume();
        }
    }//GEN-LAST:event_valorKeyTyped

    private void valorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorKeyPressed
        if(evt.getKeyCode()==10){
            evaluar();
        }
    }//GEN-LAST:event_valorKeyPressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if(ya<42){
            int xp, yp;
            xp = evt.getXOnScreen();
            yp = evt.getYOnScreen();
            move(xp - xa, yp - ya);
        }
    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        xa = evt.getX();
        ya = evt.getY();
    }//GEN-LAST:event_formMouseMoved
    public void evaluar(){
        if(Validacion.validarNombre(ingreso.getText())){
            if(!nodos.containsKey(ingreso.getText())){
                if(Validacion.validarNumero(valor.getText())){
                    estado=true;
                    this.dispose();
                }else{error2.setVisible(true);}
            }else{error.setVisible(true);}
        }
    }
    public static void print(Object o) {
        System.out.println(o);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ingresos dialog = new Ingresos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel error;
    private javax.swing.JLabel error2;
    private javax.swing.JTextField ingreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
