/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import busquedas.Arista;
import busquedas.Nodo;
import java.awt.Color;
import java.awt.Image;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Map;
import javax.swing.ImageIcon;

/**
 *
 * @author Carlos Plaza
 */
public class Principal extends javax.swing.JFrame {

    HashMap<String, int[]> nodosG;
    LinkedList<String[]> aristasG;
    HashMap<String,Nodo> nodos;
    HashMap<String,Arista> aristas;
    boolean gnodo,garista,gmove,gselect,geliminar;
    AreaGrafo grafoG;
    Resultados resultados;
    int xa,ya;
    /**
     * Creates new form Principal
     */
    public Principal() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        nodosG=new HashMap<String, int[]>();
        aristasG=new LinkedList<String[]>();
        //
        nodos=new HashMap<String, Nodo>();
        aristas=new HashMap<String,Arista>();
        grafoG=new AreaGrafo(this);
        grafoG.setBackground(Color.white);
        grafoG.setArreglos(nodosG,aristasG);
        grafoG.setArreglos2(nodos,aristas);
        grafoG.setSize(965,700);
        grafoG.setLocation(0,0);
        grafoG.setVisible(true);
        contenedor1.add(grafoG);
        gnodo=false;
        garista=false;
        gmove=false;
        gselect=false;
        geliminar=false;
        resultados = new Resultados(null, true);
        //setFondo();
        
        resultados.setLocation(this.getX()+this.getWidth()-resultados.getWidth(), this.getY()+this.getHeight()-resultados.getHeight());
    }

    public void setFondo(){
        ImageIcon imgIcon = new ImageIcon(getClass().getResource("/Icons/fondo_g.jpg"));
        Image image = imgIcon.getImage().getScaledInstance(this.getWidth()+50,this.getHeight(), Image.SCALE_SMOOTH);
        fondo.setIcon(new ImageIcon(image));
    }
    public void desactivarSeleccionNodo(){
        gnodo=false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        insertNodo = new javax.swing.JButton();
        insertArc = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        contenedor1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numN = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        numA = new javax.swing.JLabel();
        jToolBar3 = new javax.swing.JToolBar();
        eliminar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jToolBar2 = new javax.swing.JToolBar();
        move = new javax.swing.JButton();
        select = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jToolBar4 = new javax.swing.JToolBar();
        ejecutar = new javax.swing.JButton();
        ver = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        separadorTitulo = new javax.swing.JSeparator();
        power = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 800));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setToolTipText("Eliminar");
        jToolBar1.setBorderPainted(false);
        jToolBar1.setOpaque(false);

        insertNodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/nodo.png"))); // NOI18N
        insertNodo.setToolTipText("Nodo");
        insertNodo.setFocusPainted(false);
        insertNodo.setOpaque(false);
        insertNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertNodoActionPerformed(evt);
            }
        });
        jToolBar1.add(insertNodo);

        insertArc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/connectorc.png"))); // NOI18N
        insertArc.setToolTipText("Arista");
        insertArc.setOpaque(false);
        insertArc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertArcActionPerformed(evt);
            }
        });
        jToolBar1.add(insertArc);
        jToolBar1.add(jSeparator2);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 80, 43, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Graficar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 57, 59, -1));

        contenedor1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        contenedor1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contenedor1.setOpaque(false);

        javax.swing.GroupLayout contenedor1Layout = new javax.swing.GroupLayout(contenedor1);
        contenedor1.setLayout(contenedor1Layout);
        contenedor1Layout.setHorizontalGroup(
            contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
        );
        contenedor1Layout.setVerticalGroup(
            contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        getContentPane().add(contenedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 54, 970, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("#Nodos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 739, -1, -1));

        numN.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        numN.setForeground(new java.awt.Color(255, 255, 255));
        numN.setText("0");
        numN.setToolTipText("");
        getContentPane().add(numN, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 739, 53, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 739, 14, 16));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("#Aristas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 739, -1, -1));

        numA.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        numA.setForeground(new java.awt.Color(255, 255, 255));
        numA.setText("0");
        getContentPane().add(numA, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 739, 49, -1));

        jToolBar3.setFloatable(false);
        jToolBar3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar3.setToolTipText("Eliminar");
        jToolBar3.setBorderPainted(false);
        jToolBar3.setOpaque(false);

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/remove.png"))); // NOI18N
        eliminar.setToolTipText("Eliminar");
        eliminar.setFocusable(false);
        eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminar.setOpaque(false);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jToolBar3.add(eliminar);

        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/brush.png"))); // NOI18N
        limpiar.setToolTipText("Limpiar");
        limpiar.setFocusable(false);
        limpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        limpiar.setOpaque(false);
        limpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jToolBar3.add(limpiar);
        jToolBar3.add(jSeparator6);

        getContentPane().add(jToolBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 367, 39, 88));

        jToolBar2.setFloatable(false);
        jToolBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar2.setToolTipText("Eliminar");
        jToolBar2.setBorderPainted(false);
        jToolBar2.setOpaque(false);

        move.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/move.png"))); // NOI18N
        move.setToolTipText("Mover");
        move.setFocusable(false);
        move.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        move.setOpaque(false);
        move.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        move.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveActionPerformed(evt);
            }
        });
        jToolBar2.add(move);

        select.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/seleccionar.png"))); // NOI18N
        select.setToolTipText("Seleccionar");
        select.setFocusable(false);
        select.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        select.setOpaque(false);
        select.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        jToolBar2.add(select);
        jToolBar2.add(jSeparator5);

        getContentPane().add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 279, 39, -1));

        jToolBar4.setFloatable(false);
        jToolBar4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar4.setToolTipText("Eliminar");
        jToolBar4.setBorderPainted(false);
        jToolBar4.setOpaque(false);

        ejecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ejecutar.png"))); // NOI18N
        ejecutar.setToolTipText("Ejecutar");
        ejecutar.setFocusable(false);
        ejecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ejecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });
        jToolBar4.add(ejecutar);

        ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/see.png"))); // NOI18N
        ver.setToolTipText("Ver resultados");
        ver.setFocusable(false);
        ver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ver.setOpaque(false);
        ver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });
        jToolBar4.add(ver);
        jToolBar4.add(jSeparator1);

        getContentPane().add(jToolBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 179, 39, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ejecutar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 156, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 256, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Eliminar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 350, 54, -1));
        getContentPane().add(separadorTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 42, 850, 10));

        power.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/power.png"))); // NOI18N
        power.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        power.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                powerMouseClicked(evt);
            }
        });
        getContentPane().add(power, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 20, 30));

        minimizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        minimizar.setForeground(new java.awt.Color(0, 204, 0));
        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizar.setText("_");
        minimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, -1));

        titulo.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Busquedas");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 30));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tree.png"))); // NOI18N
        getContentPane().add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 54, 5, 681));

        fondo.setBackground(new java.awt.Color(102, 102, 102));
        fondo.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setOpaque(true);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1080, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertNodoActionPerformed
        garista=false;
        gmove=false;
        gselect=false;
        if (gnodo){gnodo = false;}else {gnodo = true;}
        enviarEstados();
    }//GEN-LAST:event_insertNodoActionPerformed

    private void insertArcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertArcActionPerformed
        gnodo=false;
        gmove=false;
        gselect=false;
        if (garista){garista = false;}else {garista = true;}
        enviarEstados();
    }//GEN-LAST:event_insertArcActionPerformed

    private void moveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveActionPerformed
        gnodo=false;
        garista=false;
        gselect=false;
        if(gmove){gmove=false;}else{gmove=true;}
        enviarEstados();
    }//GEN-LAST:event_moveActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        gnodo=false;
        garista=false;
        gmove=false;
        if(gselect){gselect=false;}else{gselect=true;}
        enviarEstados();
    }//GEN-LAST:event_selectActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        nodosG=new HashMap<String, int[]>();
        aristasG=new LinkedList<String[]>();
        nodos=new HashMap<String, Nodo>();
        aristas=new HashMap<String,Arista>();
        grafoG.setArreglos(nodosG,aristasG);
        grafoG.setArreglos2(nodos,aristas);
    }//GEN-LAST:event_limpiarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        
        grafoG.eliminar();
    }//GEN-LAST:event_eliminarActionPerformed

    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarActionPerformed
        formarGrafo();
        Buscar dialog = new Buscar(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        if(dialog.esValido()){
             Ejecucion ej=new Ejecucion(resultados,grafoG,nodos.get(dialog.getOrigen()), aristas,dialog.getDestinos(),nodos.size(),dialog.getTiempo(),dialog.graficar());
            ej.start();
            resultados.setVisible(true);
        }
        
        //grafoG.ejecutar();
    }//GEN-LAST:event_ejecutarActionPerformed

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        resultados.setVisible(true);
    }//GEN-LAST:event_verActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if(ya<42){
            int xp, yp;
            xp = evt.getXOnScreen();
            yp = evt.getYOnScreen();
            move(xp - xa, yp - ya);
        }
    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        xa = evt.getX();
        ya = evt.getY();
    }//GEN-LAST:event_formMouseMoved

    private void powerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_powerMouseClicked
         System.exit(0);
    }//GEN-LAST:event_powerMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(1);
    }//GEN-LAST:event_minimizarMouseClicked
    public void enviarEstados(){
        grafoG.setActividadNodo(gnodo);
        grafoG.setActividadArista(garista);
        grafoG.setMove(gmove);
        grafoG.setSelect(gselect);
        grafoG.repaint();
    }
    public static void print(Object o) {
        System.out.println(o);
    }
    public void setValueState(int numNo,int numAr){
    numN.setText(String.valueOf(numNo));
    numA.setText(String.valueOf(numAr));
    }
    public void formarGrafo(){
        reiniciar();
        Iterator<Arista> it = aristas.values().iterator();
        while(it.hasNext()){
            Arista ar=it.next();
            //ar.getNodo1();
            //print(nodos+"  "+ar.getNodo1()+"  "+ar.getNodo2());
            nodos.get(ar.getNodo1()).setNodo(nodos.get(ar.getNodo2()));
            nodos.get(ar.getNodo2()).setNodo(nodos.get(ar.getNodo1()));
        } 
        //ordenar();
    }
    public void reiniciar(){
        Iterator<Map.Entry<String, Nodo>> it = nodos.entrySet().iterator();
        while(it.hasNext()){
            Map.Entry<String, Nodo> next = it.next();
            next.getValue().reiniciar();//.ordenar(nodosG);
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor1;
    private javax.swing.JButton ejecutar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JButton insertArc;
    private javax.swing.JButton insertNodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JButton limpiar;
    private javax.swing.JLabel minimizar;
    private javax.swing.JButton move;
    private javax.swing.JLabel numA;
    private javax.swing.JLabel numN;
    private javax.swing.JLabel power;
    private javax.swing.JButton select;
    private javax.swing.JSeparator separadorTitulo;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton ver;
    // End of variables declaration//GEN-END:variables
}
