/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import busquedas.Arista;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karlo
 */
public class Resultados extends javax.swing.JDialog {
    int xa,ya;
    boolean estado=false;
    /**
     * Creates new form Resultados
     */
    public Resultados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultados = new javax.swing.JTable();
        aceptar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        elementos = new javax.swing.JLabel();
        siquiente = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        pausa = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Algoritmo", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resultados);
        if (resultados.getColumnModel().getColumnCount() > 0) {
            resultados.getColumnModel().getColumn(0).setResizable(false);
            resultados.getColumnModel().getColumn(1).setResizable(false);
            resultados.getColumnModel().getColumn(1).setPreferredWidth(30);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 109, 375, 128));

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 25, 274, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Iteracion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 53, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Metodo");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 53, 180, -1));

        elementos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        elementos.setForeground(new java.awt.Color(255, 255, 255));
        elementos.setText("Elementos");
        getContentPane().add(elementos, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 84, 375, -1));

        siquiente.setText("Siquiente");
        siquiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siquienteActionPerformed(evt);
            }
        });
        getContentPane().add(siquiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 90, -1));

        titulo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Ejecucion");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 3, -1, -1));

        pausa.setSelected(true);
        pausa.setOpaque(false);
        getContentPane().add(pausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 400, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_aceptarActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if(ya<42){
            int xp, yp;
            xp = evt.getXOnScreen();
            yp = evt.getYOnScreen();
            move(xp - xa, yp - ya);
        }
    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        xa = evt.getX();
        ya = evt.getY();
    }//GEN-LAST:event_formMouseMoved
    public boolean esPausa(){
        return pausa.isSelected();
    }
    private void siquienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siquienteActionPerformed
        if(pausa.isSelected()){
            synchronized(this){
            this.notify();}
        }
    }//GEN-LAST:event_siquienteActionPerformed
    public void setInformacion(int fila,String nombreMetodo,long tiempo){
        DefaultTableModel model=(DefaultTableModel) resultados.getModel();
        model.setValueAt(nombreMetodo, fila, 0);
        model.setValueAt(String.valueOf(tiempo)+" mseg", fila, 1);
    }
    public void setNombre(String nombreM){
        nombre.setText(nombreM);
    }
    public void setElementos(String arreglo){
        elementos.setText(arreglo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Resultados dialog = new Resultados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel elementos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nombre;
    private javax.swing.JCheckBox pausa;
    private javax.swing.JTable resultados;
    private javax.swing.JButton siquiente;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
